acq_methods = {
    "PHC": "Purchase",
    "GHC": "Gift",
    "CRHC": "Purchase",
    "MHC": "Purchase",
    "DPHC": "Purchase",
    "PPHC": "Purchase",
    "FHC": "Gift",
    "CWHC": "Purchase",
    "OHC": "Purchase",
    "AMH": "Purchase at vendor system",
    "BMH": "Purchase at vendor system",
    "CCMH": "Purchase at vendor system",
    "CWMH": "Purchase at vendor system",
    "DMH": "Purchase at vendor system",
    "EMH": "Purchase at vendor system",
    "FMH": "Purchase at vendor system",
    "GMH": "Purchase at vendor system",
    "PMH": "Purchase at vendor system",
    "PPMH": "Purchase at vendor system",
    "SOMH": "Purchase at vendor system",
    "SUMH": "Purchase at vendor system",
    "OMH": "Purchase at vendor system",
    "PUM": "Purchase",
    "GUM": "Gift",
    "AFUM": "Purchase",
    "PFUM": "Purchase",
    "AUM": "Approval",
    "DAUM": "Purchase",
    "DUM": "Purchase",
    "PXUM": "Gift",
    "NLUM": "Purchase",
    "EUM": "Exhcange",
    "EPUM": "Exchage",
    "PEUM": "Purchase",
    "FPUM": "Gift",
    "MUM": "Purchase",
    "MTUM": "Purchase",
    "CCUM": "Purchase",
    "PSC": "Purchase",
    "ASC": "Approval Plan",
    "SOSC": "Purchase",
    "SUSC": "Purchase",
    "GSC": "Gift",
    "BSC": "Purchase",
    "CSC": "Purchase",
    "CRSC": "Purchase",
    "CWSC": "Purchase",
    "DSC": "Purchase",
    "DESC": "Depository",
    "MSC": "Purchase",
    "PXSC": "Gift",
    "QSC": "Purchase",
    "NLSC": "Purchase",
    "DPSC": "Purchase",
    "PCSC": "Purchase",
    "PPSC": "Purchase",
    "ESC": "Exchange",
    "ERSC": "Exchange",
    "ESSC": "Exchange",
    "FSC": "Gift",
    "PAC": "Purchase",
    "GAC": "Gift",
    "AAC": "Approval Plan",
    "BAC": "Purchase",
    "CAC": "Purchase",
    "CRAC": "Purchase",
    "CWAC": "Purchase",
    "DAC": "Purchase",
    "DEAC": "Depository",
    "MAC": "Purchse",
    "PXAC": "Gift",
    "QAC": "Purchase",
    "NLAC": "Purchase",
    "DPAC": "Purchase",
    "PCAC": "Purchase",
    "PPAC": "Purchase",
    "EAC": "Exchange",
    "ERAC": "Exchange",
    "ESAC": "Exchange",
    "FAC": "Gift",
    "FUM": "Purchase"
}